### ISSUE TITLE
Preservation of WebAssembly.Function identity upon re-export

### ISSUE THREAD

**Issue by mstarzinger** [WebAssembly/js-types#11]
We are currently prototyping this proposal in V8 and I wanted to ask for opinions on the preservation of the object identity of a function constructed via `WebAssembly.Function` when it is re-exported by a module. Should such a re-export preserve object identity? Using a concrete example and looking at the results of the two strict equality comparisons "EQ1" and "EQ2":

```
(function TestFunctionModuleImportReExport () {
  let builder = new WasmModuleBuilder();
  let fun = new WebAssembly.Function({parameters:[], results:["i32"]}, _ => 7);
  let fun_index = builder.addImport("m", "fun", kSig_i_v)
  builder.addExport("fun1", fun_index);
  builder.addExport("fun2", fun_index);
  let instance = builder.instantiate({ m: { fun: fun }});
  console.log("EQ1", instance.exports.fun1 === instance.exports.fun2);
  console.log("EQ2", fun === instance.exports.fun1);
})();
```

The current behavior for V8 will yield "EQ1 true" and "EQ2 false" at the moment.

- For "EQ1" I see that it pretty clearly follows from step (2) in [here](https://webassembly.github.io/spec/js-api/index.html#a-new-exported-function).
- For "EQ2" I am however not entirely sure it follows from step (3.4.2) in [here](https://webassembly.github.io/spec/js-api/index.html#read-the-imports), because it's unclear whether a function constructed via `WebAssembly.Function` has an internal [[FunctionAddress]] slot.

Any thoughts on this?

**Comment by rossberg** [comment]
I think the answer should be no different from what happens if `fun` wasn't created by the constructor but taken from another module's exports. That is, `true` in both cases. So the spec will need to assign it a function address upon creation. (The spec should probably be factored such that this is done as part of the "create a host function" algorithm.)

**Comment by mstarzinger** [comment]
Thanks for the feedback, makes sense. Let me know if we should mention this briefly in the proposal text, happy to submit a PR for that. Otherwise I am fine with it just being factored accordingly in the spec.

**Comment by rossberg** [comment]
Yes, a note in the proposal might be good. A PR would be appreciated.

**Comment by mstarzinger** [comment]
Uploaded PR #12 for this.
