### ISSUE TITLE
Missing tests for subclassing WebAssembly classes

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/js-types#15]
See https://github.com/WebAssembly/spec/issues/1107 for the original issue and context.

It seems that JS API tests don't cover subclassing, which results in V8 and SpiderMonkey not implementing it correctly and returning an instance of the original class rather than subclass as mandated by the WebIDL spec.

**Comment by backes** [comment]
Shouldn't this be an issue in the current spec repo, instead of in this proposal?

**Comment by RReverser** [comment]
🤦🏻‍♂️ I shouldn't be trying to do several things at once. Thanks!
