### ISSUE TITLE
Use instance methods for type()

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/js-types#18]
Currently, the explainer has static methods, to be used like
```js
const t = WebAssembly.Table.type(table);
```
rather than the rather more ergonomic
```js
const t = table.type();
```

Apparently this was inspired by `Object` static methods such as `Object.keys`. However, the main reason to put new APIs on the `Object` constructor rather than the prototype (AFAIK) is to avoid collisions with instance properties. That doesn't apply here - we don't really expect people to put arbitrary properties on these objects. In any case, these interfaces already have all of their API on the prototype, so putting the new methods would be more consistent with that as well.

**Comment by rossberg** [comment]
The other reason to make reflection API static is to be more [mirror](https://bracha.org/mirrors.pdf)-like, in order to properly separates object capabilities from meta capabilities. That is less relevant for the Wasm API, though.
