### ISSUE TITLE
`WebAssembly.Module.{imports,exports}`

### ISSUE THREAD

**Issue by devsnek** [WebAssembly/js-types#19]
The import/export reflection APIs are nice but only provide `kind: 'global'`, without any information about what type of global is being imported/exported. Adding additional type info to this API might be within scope of this proposal.

Some additional considerations might be designing the additions with future types like gc structs being kept in mind so we don't make this harder down the road.

**Comment by rossberg** [comment]
This proposal adds exactly that. In particular, all import/export descriptors now inherent a `type` property describing the respective function/global/table/memory type. See e.g. the [example](https://github.com/WebAssembly/js-types/blob/master/proposals/js-types/Overview.md#example).

**Comment by devsnek** [comment]
Ah I was reading the rendered spec. Glad to hear this is being added :)

**Comment by rossberg** [comment]
Ah yes, AFAICT, nobody has started work on the actual spec document yet.
