### ISSUE TITLE
Backwards compatability?

### ISSUE THREAD

**Issue by 00ff0000red** [WebAssembly/js-types#24]
If I had an old Wasm module, say, today, that exported a function, would it's prototype now be `WebAssembly.Function` instead of `Function`, after this proposal is implemented?

Or, does constructing a `WebAssembly.Function` result in a plain JS `Function`?

**Comment by rossberg** [comment]
Yes, the idea is that the prototype of exported Wasm functions will change to `WA.Function.prototype`. The prototype of that is `Function.prototype`, so existing method calls and `instanceof` checks continue to work. In practice, we do not expect that to break real-world code.

**Comment by 00ff0000red** [comment]
Got it, helps to understand how this will work once/if implemented.
