### ISSUE TITLE
Allow JS functions to be directly added to via `table.set`?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/js-types#28]
See https://github.com/WebAssembly/design/issues/1408

I wonder if we can add this to this proposal.  It not only avoids having to use the WebAssembly.Function API everywhere but its more flexible because it means we don't need to know ahead of time the signature of the function being implemented in JS and it allows us to take advantage of JS polymorphism in the same way we already can for imports.

**Comment by SPY** [comment]
I believe this proposal doesn't suite a suggested change.
JS Types Reflection is focused on getting data **from** Wasm **to** JS and for that purpose `WebAssembly.Function` is introduced as a missing piece for `type()` method.
The fact `WebAssembly.Function` opens a possibility for setting JS functions to `WebAssembly.Table`s without creating a temporary module is a convenience bonus, but not a purpose of this proposal.

**Comment by sbc100** [comment]
Closing this for now.  We can continue to discuss this in WebAssembly/design#1408
