### ISSUE TITLE
JS Promise integration

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/js-types#36]
We are currently working on a proposal to support stack switching in wasm. Specifically, I am referring to the [JS Promise integration proposal](https://github.com/WebAssembly/js-promise-integration).

At the moment, we have something of a 'soft dependency' on the js-types proposal. For example, in order to signal a stack switching capability, we wrap imports and exports. A wrapped import will take a regular Promise-returning function and return a suspending version of that function; and we use WebAssembly.Function for that returned value.

However, the status of this entity is pretty hairy: it cannot be called by JS for example.

We are exploring a new style of API that does not use wrapper functions; but instead utilizes an `async` flag in the WebAssembly.Function object. This flag would have to be writeable (because we also have to mark exports which are not available until after the module is instantiated.)

If we did this, we could dramatically simplify our JS exposed API (essentially, it would disappear completely). But it would require us being able to modify the WebAssembly.Function object as described in this proposal.
The purpose of this issue is to acquire feedback from y'all about changing the js-types proposal in this way.

As a side note; this has obvious echoes of Luke's proposal to also augment WebAssembly.Function with an explicit receiver field. But other than an echo, there is no explicit interdependency as far as I am aware.

**Comment by eqrion** [comment]
I don't have any thoughts on adding an `async` flag, it would depend on exactly what it means.

I would prefer that we don't make WebAssembly.Function mutable (such as having the async flag be writable). This would require us to revoke code pointers and re-JIT optimized JS-to-Wasm call sites when a flag is written to, and we don't have that problem right now.

**Comment by fgmccabe** [comment]
I realized after I left my comment that it would not be necessary to make webassembly.function mutable. Use a constructor instead (maybe)
