### ISSUE TITLE
Limits should use 'minimum' and 'maximum' instead of 'min' and 'max' for backwards compatibility (of maximum)

### ISSUE THREAD

**Issue by aseemgarg89** [WebAssembly/js-types#5]

**Comment by rossberg** [comment]
To clarify, the actual proposal *does* use "minimum" and "maximum". The latter already exists, the former is spec'ed in the section on Naming Limits.

(The type defs in the intro are *not* the proposal. I added a small parens to clarify that the limit names also differ.)
