### ISSUE TITLE
Limits not inlined.

### ISSUE THREAD

**Issue by aseemgarg89** [WebAssembly/js-types#8]
Before this proposal, Limits have been inlined for Memory and Table types. Should we continue to inline the limits or should we allow both inlined and with explicit "limits" property. 
If we go with the latter, for backwards compatibility, inlined (at least when using 'initial') should take precedence over using 'limits' property. Please clarify.

**Comment by rossberg** [comment]
The pseudo code type definitions may be misleading, they are not themselves the proposal but merely reflect the type structure used by Wasm itself. The actual proposal is to inline the limits, see the following paragraph and descriptions.

I added a little comment hint to the pseudo code.

**Comment by aseemgarg89** [comment]
Thanks for the clarification.
